In [ ]:
!pip install datasets evaluate transformers[sentencepiece]
!apt install git-lfs

In [ ]:
#!pip install datasets
#!pip install scikit-learn
#!pip install transformers

In [ ]:
from datasets import load_dataset

cnn_dataset = load_dataset('cnn_dailymail', '3.0.0')


Generating train split:   0%|          | 0/287113 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/13368 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/11490 [00:00<?, ? examples/s]

Dataset cnn_dailymail downloaded and prepared to /root/.cache/huggingface/datasets/cnn_dailymail/3.0.0/3.0.0/1b3c71476f6d152c31c1730e83ccb08bcf23e348233f4fcc11e182248e6bf7de. Subsequent calls will reuse this data.


  0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:


# Split the dataset into smaller portions (e.g. 1/10th of the original size)
train_size = int(0.1 * len(cnn_dataset['train']))
val_size = int(0.1 * len(cnn_dataset['validation']))
test_size = int(0.1 * len(cnn_dataset['test']))

train_data = cnn_dataset['train'].train_test_split(train_size=train_size)['train']
val_data = cnn_dataset['validation'].train_test_split(train_size=val_size)['train']
test_data = cnn_dataset['test'].train_test_split(train_size=test_size)['train']

cnn_dataset['train'] = train_data
cnn_dataset['validation'] = val_data
cnn_dataset['test'] = test_data

In [ ]:
def show_samples(dataset, num_samples=3, seed=42):
    sample = dataset["train"].shuffle(seed=seed).select(range(num_samples))
    for example in sample:
        print(f"\n'>> Highlights: {example['highlights']}'")
        print(f"'>> Article: {example['article']}'")


show_samples(cnn_dataset)


'>> Highlights: Pippa's Provencal Picnic is intended as romantic meal for two .
Includes fig and goat's cheese fougasse .
Also on the menu is peach and vanilla fizz made with sparking wine .
The total cost of the menu is £60.02 for two, or £30.01 per person .
Published in Waitrose magazine as her second Friday Night Feast column .'
'>> Article: By . Claire Ellicott . PUBLISHED: . 12:18 EST, 2 May 2013 . | . UPDATED: . 09:38 EST, 3 May 2013 . Perhaps it’s all down  to her fledgling romance  with her dashing stock- broker boyfriend. Or maybe it has something to do with her younger brother James’s new relationship with television presenter Donna Air. Whatever the case, love was clearly on Pippa Middleton’s mind when she wrote her most recent recipe instalment for Waitrose – a ‘romantic picnic for two’. In the piece, the socialite sister of the Duchess of Cambridge extols the benefits of ‘whisk[ing] away someone special for an evening of gazing and grazing’. Picnic time: If your name happ

In [ ]:
cnn_dataset = cnn_dataset.filter(lambda x: len(x["highlights"].split()) > 2)


Filter:   0%|          | 0/28711 [00:00<?, ? examples/s]

Filter:   0%|          | 0/1336 [00:00<?, ? examples/s]

Filter:   0%|          | 0/1149 [00:00<?, ? examples/s]

In [ ]:
from transformers import AutoTokenizer

model_checkpoint = "google/mt5-small"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

/usr/local/lib/python3.10/dist-packages/transformers/convert_slow_tokenizer.py:454: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(


In [ ]:
max_input_length = 512
max_target_length = 30


def preprocess_function(examples):
    model_inputs = tokenizer(
        examples["article"],
        max_length=max_input_length,
        truncation=True,
    )
    labels = tokenizer(
        examples["highlights"], max_length=max_target_length, truncation=True
    )
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

In [ ]:
tokenized_datasets = cnn_dataset.map(preprocess_function, batched=True)

Map:   0%|          | 0/28711 [00:00<?, ? examples/s]

Map:   0%|          | 0/1336 [00:00<?, ? examples/s]

Map:   0%|          | 0/1149 [00:00<?, ? examples/s]

In [ ]:
from transformers import TFAutoModelForSeq2SeqLM

model = TFAutoModelForSeq2SeqLM.from_pretrained(model_checkpoint)

/usr/local/lib/python3.10/dist-packages/keras/initializers/initializers.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
All model checkpoint layers were used when initializing TFMT5ForConditionalGeneration.

All the layers of TFMT5ForConditionalGeneration were initialized from the model checkpoint at google/mt5-small.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFMT5ForConditionalGeneration for predictions without further training.


In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(tokenizer, model=model, return_tensors="tf")

In [ ]:
tokenized_datasets = tokenized_datasets.remove_columns(
    cnn_dataset["train"].column_names
)

In [ ]:
features = [tokenized_datasets["train"][i] for i in range(2)]
data_collator(features)

You're using a T5TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


{'input_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
array([[24596, 60218, 14076, ...,  9825,   259,     1],
       [ 1794,   259,   260, ...,  2426,  2621,     1]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=int32)>, 'labels': <tf.Tensor: shape=(2, 30), dtype=int32, numpy=
array([[   486,  28210,  20263,    639,    615,   7784,  63519,  30665,
          3588,    639,    776,  36930,    345,    259,    262,  19208,
          1421,    259,    260,  27936,    321,    414,  22090, 101288,
           285,    345,    514,    259,  84160,      1],
       [   298, 167405,  17438,   1070,   2101,    259,  56031,   8545,
           287,    259,   2015,    304,   2956,    305,   1001,    259,
        111754,  19514,  18295,    332,   5883,  62722,    259,    260,
          2610,   2404,    339,    288,    390,      1]], dtype=int32)>, 'decoder_input_ids': <tf.Tensor: shape=(2, 30

In [ ]:
tf_train_dataset = model.prepare_tf_dataset(
    tokenized_datasets["train"],
    collate_fn=data_collator,
    shuffle=True,
    batch_size=16,
)
tf_eval_dataset = model.prepare_tf_dataset(
    tokenized_datasets["validation"],
    collate_fn=data_collator,
    shuffle=False,
    batch_size=16,
)

/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py:388: FutureWarning: The output of `to_tf_dataset` will change when a passing single element list for `labels` or `columns` in the next datasets version. To return a tuple structure rather than dict, pass a single string.
Old behaviour: columns=['a'], labels=['labels'] -> (tf.Tensor, tf.Tensor)  
             : columns='a', labels='labels' -> (tf.Tensor, tf.Tensor)  
New behaviour: columns=['a'],labels=['labels'] -> ({'a': tf.Tensor}, {'labels': tf.Tensor})  
             : columns='a', labels='labels' -> (tf.Tensor, tf.Tensor) 
  warnings.warn(


In [ ]:
from transformers import create_optimizer
import tensorflow as tf

# The number of training steps is the number of samples in the dataset, divided by the batch size then multiplied
# by the total number of epochs. Note that the tf_train_dataset here is a batched tf.data.Dataset,
# not the original Hugging Face Dataset, so its len() is already num_samples // batch_size.
num_train_epochs = 8
num_train_steps = len(tf_train_dataset) * num_train_epochs
model_name = model_checkpoint.split("/")[-1]

optimizer, schedule = create_optimizer(
    init_lr=5.6e-5,
    num_warmup_steps=0,
    num_train_steps=num_train_steps,
    weight_decay_rate=0.01,
)

model.compile(optimizer=optimizer)

# Train in mixed-precision float16
tf.keras.mixed_precision.set_global_policy("mixed_float16")

No loss specified in compile() - the model's internal loss computation will be used as the loss. Don't panic - this is a common way to train TensorFlow models in Transformers! To disable this behaviour please pass a loss argument, or explicitly pass `loss=None` if you do not want your model to compute a loss.


In [ ]:
from transformers.keras_callbacks import PushToHubCallback

model.fit(
    tf_train_dataset,
    validation_data=tf_eval_dataset,
    epochs=1,
    callbacks=[PushToHubCallback(output_dir="./logs", token="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")],
)



ModuleNotFoundError: ignored

In [ ]:
import nltk

nltk.download("punkt")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
from tqdm import tqdm
import numpy as np
from nltk.tokenize import sent_tokenize

generation_data_collator = DataCollatorForSeq2Seq(
    tokenizer, model=model, return_tensors="tf", pad_to_multiple_of=320
)

tf_generate_dataset = model.prepare_tf_dataset(
    tokenized_datasets["validation"],
    collate_fn=generation_data_collator,
    shuffle=False,
    batch_size=8,
    drop_remainder=True,
)


@tf.function(jit_compile=True)
def generate_with_xla(batch):
    return model.generate(
        input_ids=batch["input_ids"],
        attention_mask=batch["attention_mask"],
        max_new_tokens=32,
    )


all_preds = []
all_labels = []
for batch, labels in tqdm(tf_generate_dataset):
    predictions = generate_with_xla(batch)
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    labels = labels.numpy()
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
    decoded_preds = ["\n".join(sent_tokenize(pred.strip())) for pred in decoded_preds]
    decoded_labels = ["\n".join(sent_tokenize(label.strip())) for label in decoded_labels]
    all_preds.extend(decoded_preds)
    all_labels.extend(decoded_labels)

100%|██████████| 167/167 [01:13<00:00,  2.27it/s]


In [ ]:
all_preds

['NEW South African captain AB De Villiers leaves the field after taking the wicket of Eoin Morgan during the World Cup match',
 'The youngster is playing the role as Elizabeth I in Wolf Hall.\nThe youngster is pictured on set with her mother Debbie, a',
 'NEW York Times reports that Chelsea Clinton went by the pseudonym Diane Reynolds, and Hillary Clinton went by the pseudonym Diane R',
 'NEW: Welbeck 6.5.\nReferee: Mike Jones 7.\nReferee: Mike Jones 7.\nGoal: Welbeck 48.',
 'NEW investigation.\nClinton revealed she used a personal email account.\nClinton revealed she used a personal email account.\nClinton',
 'NEW: Co-pilot Andreas Lubitz locked his captain out of the cockpit after deliberately crashed into a mountain to destroy the plane',
 'NEW: Carla Jamerson killed herself at her Las Vegas home on Friday after suffering years of being bullied at school and on social media',
 'NEW Zealand Herald reports that the man and woman involved in the office sex scandal in Christchurch.\nTh

In [ ]:
all_labels

['Evidence suggests AB de Villiers is some kind of super power.\nA man so talented in so many sports that cricket was',
 'Casting bosses hunted in vain for a little girl with curly, ginger hair.\nRunner on the show posted',
 "At the center of the controversy: Hillary Clinton's personal email account - hrd22@clintonemail.com.\nDomain",
 "Olivier Giroud diverted Danny Welbeck's header past Tim Krul to give Arsenal a 28th minute lead.",
 "Clinton said all of her 'work-related' emails from her personal account were delivered to the State Department after a '",
 'Black box voice recorder reveals chilling final moments of Airbus A320.\nPassengers are heard screaming',
 'Carla Jamerson killed herself at her Las Vegas home on Friday after suffering years of being bullied at school and on social',
 'Married senior insurance broker, 50, and junior employee, 25, involved in Christchurch office romp have lost their jobs.\nThey',
 'Chair lift at Sugarloaf Mountain Resort malfunctioned Saturday morn

In [ ]:
!pip install rouge_score

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24954 sha256=40d9f497512053e08126ee9e49ec33ab71e105eed862c56696f4237d6c5c8380
  Stored in directory: /root/.cache/pip/wheels/5f/dd/89/461065a73be61a532ff8599a28e9beef17985c9e9c31e541b4
Successfully built rouge_score


In [ ]:
import evaluate

rouge_score = evaluate.load("rouge")

In [ ]:
result = rouge_score.compute(
    predictions=decoded_preds, references=decoded_labels, use_stemmer=True
)
result = {key: value * 100 for key, value in result.items()}
{k: round(v, 4) for k, v in result.items()}

In [ ]:
result

{'rouge1': 0.18878168868942297,
 'rouge2': 0.05740392648287385,
 'rougeL': 0.15900052124378183,
 'rougeLsum': 0.17153220064003122}

In [ ]:
from transformers import pipeline

hub_model_id = "huggingface-course/mt5-small-finetuned-amazon-en-es"
summarizer = pipeline("summarization", model=model)